### ISSUE TITLE
bioSeq_extract_proteins_from_gbk does not take some plasmids

### ISSUE THREAD

**Issue by snail123815** [snail123815/thetoolbox#25]
```
'LOCUS       Exported               20533 bp DNA     circular SYN 11-APR-2023\n'
Found locus 'Exported' size '20533' residue_type 'DNA'
Some fields may be wrong.
  warnings.warn(
Traceback (most recent call last):
  File "/Users/duc/myRepos/toolbox-du/pyBioinfo/bioSeq_extract_proteins_from_gbk.py", line 14, in <module>
    faaPath = getFaaFromGbk(gbkPath)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/duc/myRepos/toolbox-du/pyBioinfo/pyBioinfo_modules/bio_sequences/protein_from_gbk.py", line 64, in getFaaFromGbk
    raise e
  File "/Users/duc/myRepos/toolbox-du/pyBioinfo/pyBioinfo_modules/bio_sequences/protein_from_gbk.py", line 60, in getFaaFromGbk
    proteins.extend(getProteins(s, codonTable=codonTable))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/duc/myRepos/toolbox-du/pyBioinfo/pyBioinfo_modules/bio_sequences/protein_from_gbk.py", line 21, in getProteins
    proteinLocustag = feat.qualifiers['locus_tag'][0]
                      ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'locus_tag'
```

**Comment by snail123815** [comment]
This also affect many bigscape gbks.
